controllers/SiteController.php
<?php

namespace app\controllers;

use yii\web\Controller;

class SiteController extends Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionJoin()
    {
        return $this->render('join');
    }

    public function actionLogin()
    {
        return $this->render('login');
    }
}

views/layouts/main.php
<?php
use app\assets\AppAsset;

AppAsset::register($this);
?>

<?php $this->beginPage(); ?>
<html>

    <head>
    <title>TodoList</title>
        <?php $this->head(); ?>
    </head>

    <body>
    <?php $this->beginBody(); ?>
    <?php
        \yii\bootstrap\NavBar::begin([
                'brandLabel' => 'ToDoIt',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                        'class' => 'navbar-default navbar-fixed-top'
                ]
        ]);
        $items = [
                ['label' => 'Join', 'url' => ['/site/join']],
                ['label' => 'Login', 'url' => ['/site/login']]
        ];
        echo \yii\bootstrap\Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => $items
        ]);
        \yii\bootstrap\NavBar::end();

    ?>
        <div class="container" style="margin-top: 50px">
        <?= $content ?>
        </div>
    <?php $this->endBody(); ?>
    </body>


</html>
<?php $this->endPage(); ?>

views/site/index.php
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>

<div class="container" style="margin-top: 50px;">
    <div class="row">
        <div class="col-md-4">
            <textarea class="form-control task-description" placeholder="Write your description..." rows="3"></textarea>
            <div class="select-and-button row" style="margin-top: 10px">
                <div class="col-md-8">
                    <select class="task-select form-control" name="task-select">
                        <option value="label-danger" class="High">High</option>
                        <option value="label-warning" class="Middle">Middle</option>
                        <option value="label-success" class="Low">Low</option>
                    </select>
                </div>
                <div class="col-md-4">
                    <button type="button" class="btn btn-success task-button" onclick="addElement()">Create a task
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <ul class="list-of-tasks">

            </ul>
        </div>
    </div>

</div>

views/site/join.php
<h1>Join us</h1>

Fill register form

views/site/login.php
<h1>Log in</h1>

Enter your e-mail and password